server:
  #  servlet:
  #     #contextPath: /auth-service
  #     contextPath: /
  port: 8080

#DB Config
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5454/icare?serverTimezone=UTC
    username : postgres
    password : root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

app:
  public-key: public_key.der
  private-key: private_key.der

cors:
  allowedOrigin: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  allowedCredentials: false
  exposeHeaders: '*'
  corsConfiguration: '/**'
